### ISSUE TITLE
Error When retrieving Paystack Payment data after successful payment

### ISSUE THREAD

**Issue by MusahMusah** [MusahMusah/laravel-multipayment-gateways#19]
Application breaks when redirecting user to the specified callback url after successful payment with paystack using the packages `redirectToCheckout` method.
**Error:**  `Typed property MusahMusah\LaravelMultipaymentGateways\Abstracts\BaseGateWay::$response must not be accessed before initialization`

**Comment by MusahMusah** [comment]
working on fix

**Comment by MusahMusah** [comment]
issue resolved

**Comment by 2pointdelivery** [comment]
Will it help if I share these gateway integration script?

[paypage-200.zip](https://github.com/user-attachments/files/18649156/paypage-200.zip)

**Comment by 2pointdelivery** [comment]
> Will it help if I share these gateway integration script?
> 
> [paypage-200.zip](https://github.com/user-attachments/files/18649156/paypage-200.zip)

@MusahMusah

**Comment by MusahMusah** [comment]
@2pointdelivery please open a new issue with a clear description of issue you're experiencing. Screenshots of your implementation and the issue would also be helpful.
